import Order from "../models/order.js";

export async function CreateOrder(req,res){
    //get user infromation
    if(req.user == null){
        res.status(403).json({message : "User not found"});
        return
    }

    const orderInfo = req.body
    if(orderInfo.name == null){
        orderInfo.name = req.user.firstName + " " + req.user.lastName
    }

    let orderId = "CBC000001"

    const lasrOrder = await Order.find().sort({date : -1}).limit(1)
    if(lasrOrder.length > 0){
        const lastorderId = lasrOrder[0].orderId

        const lastOrderNumberString = lastorderId.replace("CBC","")
        const lastOrderNumber = parseInt(lastOrderNumberString)
        const newOrderNumber = lastOrderNumber + 1
        const newOrderNumberString = String(newOrderNumber).padStart(5,"0")
        orderId = "CBC" + newOrderNumberString
    }

    const order = new Order({
        orderId : orderId,
        email : req.user.email,
        name : orderInfo.name,
        address : orderInfo.address,
        total : 0,
        phone : orderInfo.phone,
        products :[]
})
try{
   const CreateOrder = await order.save()
   res.json({
    message : "Order created successfully",
    order : CreateOrder
   })
}catch(err){
    res.json({message : "Failed to create order", error : err});
}

    //add current user if not provided
    //orderId generated by system
    //create order
}